Increase verbosity, ping 8.8.4.4

diff --git a/.github/workflows/check-ping-group-range.yml b/.github/workflows/check-ping-group-range.yml
--- a/.github/workflows/check-ping-group-range.yml
+++ b/.github/workflows/check-ping-group-range.yml
@@ -25,9 +25,6 @@ jobs:
         run: |
           echo "Current ping_group_range setting:"
           sysctl net.ipv4.ping_group_range || echo "Setting not available"
-
-      - name: Print Ping Group Range from Proc
-        run: |
           if [ -f /proc/sys/net/ipv4/ping_group_range ]; then
             echo "Ping group range from /proc/sys/net/ipv4/ping_group_range:"
             cat /proc/sys/net/ipv4/ping_group_range
@@ -38,14 +35,23 @@ jobs:
       - name: Test Unprivileged Ping
         run: |
           echo "Testing unprivileged ping to 127.0.0.1..."
-          ping -c 1 -W 1 127.0.0.1 || echo "Unprivileged ping failed"
+          ping -c 1 -W 1 8.8.4.4 || echo "Unprivileged ping failed"
 
       - name: Increase Ping Group Range
         run: |
           echo "Increasing ping_group_range to 0 2147483647"
           sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"
 
+          echo "Current ping_group_range setting:"
+          sysctl net.ipv4.ping_group_range || echo "Setting not available"
+          if [ -f /proc/sys/net/ipv4/ping_group_range ]; then
+            echo "Ping group range from /proc/sys/net/ipv4/ping_group_range:"
+            cat /proc/sys/net/ipv4/ping_group_range
+          else
+            echo "Ping group range file does not exist"
+          fi
+
       - name: Test Unprivileged Ping After Change
         run: |
           echo "Testing unprivileged ping after changing ping_group_range..."
-          ping -c 1 -W 1 127.0.0.1 || echo "Unprivileged ping failed after changing ping_group_range"
+          ping -c 1 -W 1 8.8.4.4 || echo "Unprivileged ping failed after changing ping_group_range"
